gText_Birch_Welcome:: @ 82C897B
	.string "Hi! This is me... HanuP!\p"
	.string "Welcome to Pokemon Arclight!\p"
	.string "This game is for non-commercial purposes.\n"
	.string "If you paid for this, then get a refund!\p"
	.string "This game is rated PG-14,\n"
	.string "due to violence and harsh truths\p"
	.string "of reality!$"
	

gText_Birch_Pokemon:: @ 82C89FB
	.string "Let me show you a Pokemon\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
   
	.string "In order for you to enjoy this game,\n"
	.string "I RECOMMEND YOU TO PLAY THIS ON A PC!\p"
	
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Tell me...\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to \n"
	.string "FOLIA TOWN.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where harsh,\l"
	.string "reality, and gory await!\p"
	.string "Well, Let the adventure begin!\n"
	
	.string "$"
